# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    id_store:
        class: AppBundle\Store\IdStore
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml.system.time_provider"

    user_creator:
        class: AppBundle\Security\User\UserCreator
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml_sp.username_mapper.simple"
